version: "3"
services:
  db:
    build:
      # Dockerfile path
      context: .
      dockerfile: ./docker/mysql/Dockerfile
    ports:
      - "3306:3306"
    volumes:
      - ./docker/mysql/db:/docker-entrypoint-initdb.d
      - ./docker/mysql/db/mysql_data:/var/lib/mysql
    env_file:
      - "./.env"

  api:
    build:
      context: .
      dockerfile: ./docker/api/Dockerfile
    volumes:
      - ./:/go/src/github.com/satorunooshie/user-rest-api
    ports:
      - "8080:8080"
    depends_on:
      - db
