CREATE DATABASE IF NOT EXISTS user_rest_api;
USE user_rest_api;

CREATE TABLE IF NOT EXISTS users (
    id         INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
    name       VARCHAR(190) NOT NULL,
    password   VARCHAR(190) NOT NULL,
    age        INT NOT NULL,
    height     INT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    updated_at TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deleted_at TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8
